CREATE TABLE IF NOT EXISTS USERS (
  id BIGSERIAL NOT NULL PRIMARY KEY,
  nickname VARCHAR(128) UNIQUE,
  fullname VARCHAR(128),
  about TEXT,
  email VARCHAR(128) UNIQUE
);

CREATE TABLE IF NOT EXISTS FORUMS (
  id BIGSERIAL NOT NULL PRIMARY KEY,
  tittle VARCHAR(128),
  slug VARCHAR(128) UNIQUE,
  user_id BIGINT REFERENCES USERS(id),
  posts BIGINT,
  threads BIGINT
);

CREATE TABLE IF NOT EXISTS THREADS (
  id BIGSERIAL NOT NULL PRIMARY KEY,
  tittle VARCHAR(128),
  author BIGINT  REFERENCES USERS(id),
  forum BIGINT REFERENCES FORUMS(id),
  message TEXT,
  slug VARCHAR(128) UNIQUE,
  created TIMESTAMP,
  votes BIGINT
);

CREATE TABLE IF NOT EXISTS POSTS (
  id BIGSERIAL NOT NULL PRIMARY KEY,
  parent BIGINT REFERENCES POSTS(id),
  author BIGINT REFERENCES USERS(id),
  thread BIGINT REFERENCES THREADS(id),
  forum BIGINT REFERENCES FORUMS(id),
  message TEXT,
  isedited BOOLEAN,
  created TIMESTAMP
);